PROCESS BEFORE OUTPUT.

*&SPWIZARD: PBO FLOW LOGIC FOR TABLECONTROL 'ZTC_DISPLAY'
  MODULE ZTC_DISPLAY_CHANGE_TC_ATTR.
*&SPWIZARD: MODULE ZTC_DISPLAY_CHANGE_COL_ATTR.
  LOOP AT   GT_VBAK
       INTO GS_VBAK
       WITH CONTROL ZTC_DISPLAY
       CURSOR ZTC_DISPLAY-CURRENT_LINE.
    MODULE ZTC_DISPLAY_GET_LINES.
*&SPWIZARD:   MODULE ZTC_DISPLAY_CHANGE_FIELD_ATTR
  ENDLOOP.

*&SPWIZARD: PBO FLOW LOGIC FOR TABLECONTROL 'ZTC_EDIT_VAR'
  MODULE ZTC_EDIT_VAR_CHANGE_TC_ATTR.
*&SPWIZARD: MODULE ZTC_EDIT_VAR_CHANGE_COL_ATTR.
  LOOP AT   GT_VARIANT_DATA
       INTO GS_VARIANT_DATA
       WITH CONTROL ZTC_EDIT_VAR
       CURSOR ZTC_EDIT_VAR-CURRENT_LINE.
    MODULE ZTC_EDIT_VAR_GET_LINES.
*&SPWIZARD:   MODULE ZTC_EDIT_VAR_CHANGE_FIELD_ATTR
  ENDLOOP.

 MODULE STATUS_0100.
*
PROCESS AFTER INPUT.

*&SPWIZARD: PAI FLOW LOGIC FOR TABLECONTROL 'ZTC_DISPLAY'
  LOOP AT GT_VBAK.
    CHAIN.
      FIELD GS_VBAK-VBELN.
      FIELD GS_VBAK-ERDAT.
      FIELD GS_VBAK-VBTYP.
    endchain.
    FIELD GS_VBAK-SEL_FLAG.
      MODULE ZTC_DISPLAY_MARK.
  ENDLOOP.
  MODULE filter_data.
  MODULE validate.
  MODULE ZTC_DISPLAY_USER_COMMAND.
*&SPWIZARD: MODULE ZTC_DISPLAY_CHANGE_TC_ATTR.
*&SPWIZARD: MODULE ZTC_DISPLAY_CHANGE_COL_ATTR.



*&SPWIZARD: PAI FLOW LOGIC FOR TABLECONTROL 'ZTC_EDIT_VAR'
  LOOP AT GT_VARIANT_DATA.
    CHAIN.
      FIELD GS_VARIANT_DATA-VBELN.
      FIELD GS_VARIANT_DATA-VARIA.
      FIELD GS_VARIANT_DATA-VARF_N.
      FIELD GS_VARIANT_DATA-VBTYP.
      MODULE ZTC_EDIT_VAR_MODIFY ON CHAIN-REQUEST.
    endchain.
    FIELD GS_VARIANT_DATA-SEL_FLAG
      MODULE ZTC_EDIT_VAR_MARK ON REQUEST.
  ENDLOOP.
  MODULE update_variant_fn.
  MODULE ZTC_EDIT_VAR_USER_COMMAND.
*&SPWIZARD: MODULE ZTC_EDIT_VAR_CHANGE_TC_ATTR.
*&SPWIZARD: MODULE ZTC_EDIT_VAR_CHANGE_COL_ATTR.


* MODULE USER_COMMAND_0100.