PROCESS BEFORE OUTPUT.
*&SPWIZARD: PBO FLOW LOGIC FOR TABLECONTROL 'ZTC_MULTI_VAR'
  MODULE ZTC_MULTI_VAR_CHANGE_TC_ATTR.
*&SPWIZARD: MODULE ZTC_MULTI_VAR_CHANGE_COL_ATTR.
  LOOP AT   GT_MULTIPLE_VARIANT_DEF
       INTO GS_MULTIPLE_VARIANT_DEF
       WITH CONTROL ZTC_MULTI_VAR
       CURSOR ZTC_MULTI_VAR-CURRENT_LINE.
    MODULE ZTC_MULTI_VAR_GET_LINES.
*&SPWIZARD:   MODULE ZTC_MULTI_VAR_CHANGE_FIELD_ATTR
  ENDLOOP.

 MODULE STATUS_0200.
*
PROCESS AFTER INPUT.
*&SPWIZARD: PAI FLOW LOGIC FOR TABLECONTROL 'ZTC_MULTI_VAR'
  LOOP AT GT_MULTIPLE_VARIANT_DEF.
    CHAIN.
      FIELD GS_MULTIPLE_VARIANT_DEF-VBELN.
      FIELD GS_MULTIPLE_VARIANT_DEF-VARIA.
      FIELD GS_MULTIPLE_VARIANT_DEF-VARF_N.
      FIELD GS_MULTIPLE_VARIANT_DEF-ERDAT.
      FIELD GS_MULTIPLE_VARIANT_DEF-NETWR.
      FIELD GS_MULTIPLE_VARIANT_DEF-VBTYP.
      MODULE ZTC_MULTI_VAR_MODIFY ON CHAIN-REQUEST.
    endchain.
    FIELD GS_MULTIPLE_VARIANT_DEF-SEL_FLAG
      MODULE ZTC_MULTI_VAR_MARK ON REQUEST.
  ENDLOOP.
  MODULE update_multiple_var.
  MODULE ZTC_MULTI_VAR_USER_COMMAND.
*&SPWIZARD: MODULE ZTC_MULTI_VAR_CHANGE_TC_ATTR.
*&SPWIZARD: MODULE ZTC_MULTI_VAR_CHANGE_COL_ATTR.

 MODULE USER_COMMAND_0200.