*&---------------------------------------------------------------------*
*& Report ZPRG_EVENTS
*&---------------------------------------------------------------------*
*&
*&---------------------------------------------------------------------*
REPORT ZPRG_EVENTS.

TABLES : LIKP, LIPS.

TYPES : BEGIN OF TY_LIKP,
  VBELN TYPE VBELN_VL,
  ERDAT TYPE ERDAT,
  VKORG TYPE VKORG,
  VBTYP TYPE VBTYPL,
  KUNNR TYPE KUNWE,
  END OF TY_LIKP.

 TYPES : BEGIN OF TY_LIPS,
  VBELN TYPE VBELN_VL,
  POSNR TYPE POSNR_VL,
  MATNR TYPE MATNR,
  WERKS TYPE WERKS_D,
  END OF TY_LIPS.

TYPES : BEGIN OF TY_FINAL,
        VBELN TYPE VBELN_VL,
  ERDAT TYPE ERDAT,
  VKORG TYPE VKORG,
  VBTYP TYPE VBTYPL,
  KUNNR TYPE KUNWE,
  POSNR TYPE POSNR_VL,
  MATNR TYPE MATNR,
  WERKS TYPE WERKS_D,
  END OF TY_FINAL.

  DATA : IT_LIKP TYPE TABLE OF TY_LIKP,
        WA_LIKP TYPE TY_LIKP.
  DATA : IT_LIPS TYPE TABLE OF TY_LIPS,
        WA_LIPS TYPE TY_LIPS.
  DATA : IT_FINAL TYPE TABLE OF TY_FINAL,
        WA_FINAL TYPE TY_FINAL.

  SELECTION-SCREEN BEGIN OF BLOCK B1 WITH FRAME TITLE T1.
    SELECT-OPTIONS : P_VBELN FOR LIKP-VBELN.
    SELECTION-SCREEN END OF BLOCK B1.

    INITIALIZATION.
    T1 = 'DELIVERY CHALLAN'.

    START-OF-SELECTION.

    SELECT * FROM LIKP INTO CORRESPONDING FIELDS OF TABLE IT_LIKP
      WHERE VBELN IN P_VBELN .

IF IT_LIPS IS NOT INITIAL.

      SELECT * FROM LIPS INTO CORRESPONDING FIELDS OF TABLE IT_LIPS
        FOR ALL ENTRIES IN IT_LIKP
        WHERE  VBELN = IT_LIKP-VBELN.

ENDIF.

LOOP AT IT_LIKP INTO WA_LIKP.
  LOOP AT IT_LIKP INTO WA_LIKP WHERE VBELN = WA_LIKP-VBELN.
    WA_FINAL-VBELN = WA_LIKP-VBELN.
    WA_FINAL-ERDAT = WA_LIKP-ERDAT.
    WA_FINAL-VKORG = WA_LIKP-VKORG.
    WA_FINAL-VBTYP = WA_LIKP-VBTYP.
    WA_FINAL-KUNNR = WA_LIKP-KUNNR.
    WA_FINAL-POSNR = WA_LIPS-POSNR.
    WA_FINAL-MATNR = WA_LIPS-MATNR.
    WA_FINAL-WERKS = WA_LIPS-WERKS.
APPEND WA_FINAL TO IT_FINAL.
CLEAR : WA_FINAL.
  ENDLOOP.

ENDLOOP.

LOOP AT IT_FINAL INTO WA_FINAL.

WRITE : / WA_FINAL-VBELN , WA_FINAL-ERDAT , WA_FINAL-VKORG , WA_FINAL-VBTYP ,
          WA_FINAL-KUNNR , WA_FINAL-POSNR , WA_FINAL-MATNR , WA_FINAL-WERKS.
ENDLOOP.
